[tool.poetry]
name = "dddpy"
version = "0.1.0"
description = "Enforce tactical DDD to promote maintainable code"
authors = ["Tom Coathup <github@tom-ac.dev>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^8.1.1"
